### ISSUE TITLE
TypeError on EventEmmitter() in Datasource.js as line 36

### ISSUE THREAD

**Issue by peterlavin** [LinkedDataFragments/Server.js#33]
Hi Ruben, running v0.10.29 on Debian 8, installed using apt-get and getting the following error on starting. Searching around, this error appears with EventEmitter in other places, have you come across it?

```
$` ldf-server config.json 5000 4

/usr/local/lib/node_modules/ldf-server/lib/datasources/Datasource.js:36
Datasource.prototype = new EventEmitter();
                       ^
TypeError: object is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/ldf-server/lib/datasources/Datasource.js:36:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ldf-server/lib/datasources/MemoryDatasource.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by RubenVerborgh** [comment]
Hi Peter, great you're giving the server a try!
Node 0.10.29 is hugely outdated; I just specified the minimum requirement of Node 4.0 explicitly in the config with 0fa68551e989e646f843797b11503c36186d6148.

You may want to follow these [instructions to install Node 4.x (or 6.x) on Debian](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

**Comment by peterlavin** [comment]
Hi Ruben, yes, upgrading to 4.x has fixed the problem, thanks,
P.
