### ISSUE TITLE
COUNT query failed

### ISSUE THREAD

**Issue by jo-tud** [LinkedDataFragments/Server.js#85]
We configured a remote data source with a SPARQL endpoint (`https://example.io/sparql`). When trying to view the configured data source the following error is shown:
```
Error accessing SPARQL endpoint https://example.io/sparql: COUNT query failed.
```
This is shown in the console:
```
$ ldf-server config.json 5000 4
Master 7667 running on http://localhost:5000/.
Worker 7687 running on http://localhost:5000/.
Worker 7681 running on http://localhost:5000/.
Worker 7674 running on http://localhost:5000/.
Worker 7676 running on http://localhost:5000/.
Error: Error accessing SPARQL endpoint https://example.io/sparql: COUNT query failed.
    at emitError (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/ldf-server/lib/datasources/SparqlDatasource.js:71:40)
    at /home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/ldf-server/lib/datasources/SparqlDatasource.js:64:7
    at Request.<anonymous> (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/ldf-server/lib/datasources/SparqlDatasource.js:94:7)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/ldf-server/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I'd like to identify the cause of this error but it seems the necessary information is not logged.
Any ideas?

**Comment by RubenVerborgh** [comment]
> We configured a remote data source with a SPARQL endpoint (`https://example.io/sparql`).

Is this a real endpoint?
Because that would be a good reason why it fails :-)

**Comment by rubensworks** [comment]
Considering this resolved, please comment should this not be the case.
